# Generated by Django 2.0.2 on 2018-02-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='user_id',
        ),
    ]
