# Generated by Django 2.0.2 on 2018-02-09 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20180209_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='user',
        ),
    ]
