# Generated by Django 2.0.2 on 2018-02-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_auto_20180209_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
